### ISSUE TITLE
Can you help answer the following question? Thank you.

### ISSUE THREAD

**Issue by XuanX-new** [GC-WSL/MOL#4]
Loaded dataset `NWPU_train` for training
Set proposal method: selective_search
Appending horizontally-flipped training examples...
NWPU_train gt roidb loaded from /disk2/summer/MOL-main/MOL-1/data/cache/NWPU_train_gt_roidb.pkl
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/trainval_net.py", line 73, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/trainval_net.py", line 73, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/trainval_net.py", line 71, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/disk2/summer/MOL-main/MOL-1/tools/../lib/model/train_val.py", line 312, in get_training_roidb
    imdb.append_flipped_images()
  File "/disk2/summer/MOL-main/MOL-1/tools/../lib/datasets/imdb.py", line 107, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/disk2/summer/MOL-main/MOL-1/tools/../lib/datasets/imdb.py", line 68, in roidb
    self._roidb = self.roidb_handler()
  File "/disk2/summer/MOL-main/MOL-1/tools/../lib/datasets/NWPU.py", line 146, in selective_search_roidb
    ss_roidb = self._load_selective_search_roidb(gt_roidb)
  File "/disk2/summer/MOL-main/MOL-1/tools/../lib/datasets/NWPU.py", line 186, in _load_selective_search_roidb
    ind =raw_name.index(self._image_index[i])
ValueError: '000391' is not in list

**Comment by GC-WSL** [comment]
Please check your data path is correct. Or you can try to modify "TRAIN_IMDB=NWPU_train+NWPU_val" to "TRAIN_IMDB=NWPU_trainval" in train_30000.sh.

**Comment by XuanX-new** [comment]
Thank you for your reply. I will try this.

**Comment by ucasyjz** [comment]
> Thank you for your reply. I will try this.

I have a question, if you have the NWPUv2 and help me download?
